In [1]:
# PRE-REQUISITE

import pandas as pd

**CHALLENGE 1**

Given the dataset from the URL: https://afterwork.ai/ds/ch/factory_imclo.csv, create a code snippet using filtering rows with loc to extract factories that have a production capacity greater than 10,000. Display the Factory ID, Factory Name, Location, and Production Capacity of the filtered factories.

In [2]:
# Loading the dataset from the provided URL
df_1 = pd.read_csv('https://afterwork.ai/ds/ch/factory_imclo.csv')


df_1.loc[df_1['Production Capacity']>10000,['Factory ID', 'Factory Name', 'Location','Production Capacity']].head()

   Factory ID       Factory Name       Location  Production Capacity
2       F1003  123 Manufacturing        Chicago                12000
6       F1007  JKL Manufacturing  San Francisco                11000
10      F1011        GHI Factory         Denver                10500
16      F1017  JKL Manufacturing      Charlotte                11200
19      F1020        GHI Factory      Nashville                10600

**CHALLENGE 2**

Create a crosstab table to analyze the relationship between 'Product Category' and 'Payment Method' in the sales dataset available at the following URL: https://afterwork.ai/ds/ch/sales_habqo.csv. This will help you understand how different product categories are being purchased based on the payment method used.

In [ ]:
# Loading the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/ch/sales_habqo.csv')


# Creating a crosstab table to analyze the relationship between Product Category and Payment Method
pd.crosstab(df['Product Category'],df['Payment Method'])

Payment Method    Cash  Credit Card  Debit Card  PayPal
Product Category
Clothing             5            6           6       6
Electronics          6            6           6       6
Home Appliances      6            6           6       6

**CHALLENGE 3**

Using the dataset from the URL: https://afterwork.ai/ds/ch/sales_ktwnq.csv, write a Python code snippet that filters out all rows where the 'Product Name' column contains the word 'Watch'. Display the filtered DataFrame.

In [7]:
# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/ch/sales_ktwnq.csv')
df[df["Product Name"].str.contains("Watch",case=False)].head()

,Order ID,Customer Name,Product Name,Category,Quantity,Unit Price,Total Price,Order Date,Shipping Address,City
8,1009,Mark Thompson,Watch,Accessories,1,150,150,2021-05-30,852 Pineapple St,Atlanta
18,1019,Brandon Green,Running Watch,Accessories,1,90,90,2021-06-25,852 Apple St,Tampa
20,1021,Andrew White,Smart Watch,Electronics,1,200,200,2021-06-30,753 Orange St,Los Angeles
28,1029,Scott Parker,Watch,Accessories,2,150,300,2021-07-20,258 Pineapple St,Boston
38,1039,Keith Rivera,Running Watch,Accessories,2,90,180,2021-08-15,258 Orange St,Charlotte

In [ ]:
bin_edges = list(range(0,1051,50))

print(bin_edges)


bin_labels = [f"{bin_edges[i] if i==0 else bin_edges[i]+1}-{bin_edges[i+1]}" for i in range(len(bin_edges)-1)]

print(bin_labels)

[0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050]
['0-50', '50-100', '100-150', '150-200', '200-250', '250-300', '300-350', '350-400', '400-450', '450-500', '500-550', '550-600', '600-650', '650-700', '700-750', '750-800', '800-850', '850-900', '900-950', '950-1000', '1000-1050']

**CHALLENGE 4**

Using the dataset from the URL: https://afterwork.ai/ds/ch/sales_gc6tu.csv, create a new categorical column in the DataFrame by binning the 'Total Price' data into three bins: 'Low', 'Medium', and 'High'. Analyze the sales data based on these price categories. Remember to specify the data to be binned, define the bin edges or categories, and use pd.cut to create the new categorical column.

In [32]:
# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/ch/sales_tn8b1.csv')

# create bins

dbins_labels = ['Low','Medium','High']

dbins= list(range(0,1201,400))

print(dbins)

df["binned_prices"] =pd.cut(df["Total Price"],bins = dbins,labels = dbins_labels,include_lowest=True)

df.head()

[0, 400, 800, 1200]

,Order ID,Customer Name,Product Category,Product Name,Quantity,Unit Price,Total Price,Discount,Shipping Address,Order Date,binned_prices
0,1001,John Doe,Electronics,Smartphone,2,500,1000,0.10,New York,2021-05-15,High
1,1002,Jane Smith,Home Appliances,Refrigerator,1,800,800,0.05,Los Angeles,2021-06-20,Medium
2,1003,Michael Johnson,Clothing,T-Shirt,5,20,100,0.00,Chicago,2021-07-10,Low
3,1004,Emily Brown,Electronics,Headphones,3,50,150,0.15,Miami,2021-08-25,Low
4,1005,David Wilson,Home Appliances,Washing Machine,1,600,600,0.10,Houston,2021-09-30,Medium

In [24]:
df.describe()

          Order ID   Quantity  Unit Price  Total Price   Discount
count    75.000000  75.000000   75.000000    75.000000  75.000000
mean   1038.000000   1.573333  108.200000   132.533333   0.072000
std      21.794495   0.932496  159.048352   179.431108   0.057092
min    1001.000000   1.000000    5.000000    10.000000   0.000000
25%    1019.500000   1.000000   30.000000    50.000000   0.000000
50%    1038.000000   1.000000   60.000000    80.000000   0.100000
75%    1056.500000   2.000000   85.000000   120.000000   0.100000
max    1075.000000   5.000000  800.000000  1000.000000   0.200000

**CHALLENGE 5**

Given the dataset from the URL: https://afterwork.ai/ds/ch/sales_915lw.csv, create a code snippet that maps the 'Category' column values to their corresponding department codes using a dictionary. Replace the existing category names with the department codes based on the predefined mapping.

In [ ]:
# Define a dictionary for mapping values from 'Category' to department codes
category_mapping = {
    'Electronics': 'ELEC',
    'Clothing': 'CLOTH',
    'Furniture': 'FURN',
    'Office Furniture':'FURN',
    'Books': 'BOOKS',
    'Toys': 'TOYS',
    'Sports': 'SPORTS',
}

# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/ch/sales_915lw.csv')

# Apply the mapping to the 'Category' column in the DataFrame
df['new_category'] = df['Product Name'].map(category_mapping)
df.head()

,Order ID,Customer Name,Product Name,Category,Quantity,Unit Price,Total Price,Discount,Order Date,Shipping Address,new_category
1001,John Doe,Laptop,Electronics,2,1200,2400,0.10,2021-05-10,123 Main St,New York,ELEC
1002,Jane Smith,Headphones,Electronics,3,50,150,0.05,2021-05-12,456 Elm St,San Francisco,ELEC
1003,Michael Johnson,Desk,Office Furniture,1,300,300,0.00,2021-05-15,789 Oak St,Chicago,FURN
1004,Sarah Brown,Printer,Electronics,1,200,200,0.00,2021-05-18,321 Pine St,Los Angeles,ELEC
1005,David Lee,Chair,Office Furniture,4,75,300,0.20,2021-05-20,555 Cedar St,Seattle,FURN

**CHALLENGE 6**

Given the dataset of products available at the URL: https://afterwork.ai/ds/ch/products_v9oui.csv, create a function that calculates the total revenue generated by each product by multiplying the 'Price' and 'Stock Quantity' attributes. Apply this function to every row in the dataset and store the results in a new column named 'Total Revenue'.

In [36]:
# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/ch/products_v9oui.csv')
df.head()

,Product ID,Product Name,Category,Brand,Price,Stock Quantity,Supplier,Rating,Discount,Expiry Date
0,1001,Laptop,Electronics,Dell,1200,50,ABC Electronics,4.5,10%,2023-05-15
1,1002,Headphones,Electronics,Sony,100,100,XYZ Gadgets,4.2,5%,2024-08-20
2,1003,Smartphone,Electronics,Samsung,800,75,PQR Tech,4.7,15%,2023-12-31
3,1004,Watch,Fashion,Rolex,5000,20,Timepieces Inc,4.9,20%,2025-02-28
4,1005,Shoes,Fashion,Nike,120,150,Sports Gear Ltd,4.3,10%,2024-10-10

In [43]:
def total_revenue(group):
    revenue = group["Price"]*group["Stock Quantity"]
    return revenue.sum()


summary = df.groupby('Product Name').apply(total_revenue)

summ = pd.DataFrame(summary)

summ.T

C:\Users\HOSEA\AppData\Local\Temp\ipykernel_3152\3220750297.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary = df.groupby('Product Name').apply(total_revenue)

Product Name,Backpack,Book,Calculator,Candle,Chair,Desk,Desk Calendar,Desk Chair,Desk Clock,Desk Fan,...,Tablet,Throw Blanket,Throw Pillow,USB Flash Drive,Wall Art,Wall Clock,Wallet,Watch,Water Bottle,Wireless Charger
0,10000,2000,2800,2000,2000,4500,5200,9000,2800,3750,...,14000,7200,7800,8100,6750,5000,12000,107000,3000,3750